export const TOTAL_ITEM_CART = 'total_item_cart';
export const TAB_LOGIN = 'tab_login';
// SNACKBAR
export const ONCHANGE_SNACKBAR = 'ONCHANGE_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';

// LOGIN AND REGISTER
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
// GET USER
export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
